### ISSUE TITLE
chifra abis --find with many searches fails

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1873]
Search for `// TODO: see issue #1873`

Uncomment the `wg.Done()` and `return` lines. Comment out the `os.Exit()` line

Run this command:

```
chifra abis --find 0x1aa3a008 --find 0x3ccfd60b --find 0xad7a672f --find 0xc3c5a547 --find 0xa07f3a56 --find 0x6ded82f8 --find 0xea8a1af0 --find 0x52efea6e --find 0x9989a5ae --find 0x5353a2d8 --find 0xc2a2ce06 --find 0xe17e082b --find 0x65a31545 --find 0x9d76ea58 --find 0x1c4e23de8d72c94b22992bd4d7b6786b215ba876af214ff63e6a0ca38fc97af4 --find 0x631ff1c4e1a02c54b480a34b810e03bcee61fe38efcb243930a7f820914923e2 --find 0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0 --find 0x4d509eaf411f241400f13f5abf136c29e58fc43af0f27f87a1c1c9767795d03f --find 0x61ed07cde244eab019f88846ecbec7e89ca54396f1f2ee4d1a82785e4c8bbf1d --find 0x5dba113b49cfa7c90315e8e604e6b506f7abcb909b01dcb19ec39005086e68fc --find 0xe933406ce445ea24d84ca4529e514adc8926e62cdc8b5a67c568c9fd578f1a8a --find 0x61355a34c3bc2e502a24eba7ad2fb0fd0d05c4f71de8cb041fbe39cd3649665e --find 0xe7fc560b4d0182164d7320ccef844dcc3375441f095669f48dbd47915ebbde68 --find 0x8da5cb5b --find 0x06fdde03 --find 0xd0e30db0 --find 0x6d006ae8 --find 0x2de40ce3 --find 0x12fa6feb --find 0x9a82a09a --find 0x3d6a71e4 --find 0x7238f361 --find 0x9328beee --find 0x6b46c8c3 --find 0x09e69ede --find 0x9b25cacb --find 0xf2fde38b --find 0x1e3c9352 --find 0x05f203d9 --find 0x31ae450b --find 0x0191dc92 --find 0x24d7806c --find 0x1aa3a008 --find 0x3ccfd60b --find 0xad7a672f --find 0xc3c5a547 --find 0xa07f3a56 --find 0x6ded82f8 --find 0xea8a1af0 --find 0x52efea6e --find 0x9989a5ae --find 0x5353a2d8 --find 0xc2a2ce06 --find 0xe17e082b --find 0x9d76ea58 --find 0x57d380dbcddc47e0e592a9fd9ac9ab20c72572944143ef72b0e201536e0174f9 --find 0x8acc1774 --find 0x2be72cd5 --find 0x83197ef0 --find 0xf5074f41 --find 0xad7a672f --find 0x3381114b --find 0x65a31545 --find 0x9d76ea58 --find 0x2be72cd5 --find 0xad7a672f --find 0x3381114b --find 0x65a31545 --find 0x9d76ea58 --find 0x2be72cd5 --find 0x1c4e23de8d72c94b22992bd4d7b6786b215ba876af214ff63e6a0ca38fc97af4 --find 0x631ff1c4e1a02c54b480a34b810e03bcee61fe38efcb243930a7f820914923e2 --find 0x1e3c9352 --find 0x05f203d9 --find 0x31ae450b --find 0x0191dc92 --find 0x24d7806c --find 0xfdacd576 --find 0x0900f010 --find 0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0 --find 0xf2fde38b
```

Get this result (we mismanage wait groups):

"0x9d76ea58","tokenAddress()"
2021/11/03 21:08:40 worker with func exits from a panic: sync: negative WaitGroup counter
2021/11/03 21:08:40 worker with func exits from panic: goroutine 41 [running]:
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1.1(0xc0002ea870)
	/Users/jrush/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker_func.go:58 +0x17c
panic(0x454bd60, 0x46a4460)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
sync.(*WaitGroup).Add(0xc000304e10, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x147
sync.(*WaitGroup).Done(0xc000304e10)
	/usr/local/go/src/sync/waitgroup.go:99 +0x34
github.com/TrueBlocks/trueblocks-core/src/apps/chifra/cmd/abis.HandleFind.func1(0x454bd60, 0xc00020d3e0)
	/Users/jrush/Development/trueblocks-core/src/apps/chifra/cmd/abis/handle_find.go:73 +0x1bb
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1(0xc0002ea870)
	/Users/jrush/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker_func.go:70 +0xb0
created by github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run
	/Users/jrush/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker_func.go:48 +0x4c

"0xad7a672f","totalBalance()"

**Comment by tjayrush** [comment]
No longer fails.
